name: Install zizmor

on:
  workflow_dispatch:  # Permite executar o workflow manualmente

jobs:
  install-zizmor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install zizmor
        run: |
          cargo install --git https://github.com/woodruffw/zizmor
      
      - name: Run zizmor offline scan (no exit code)
        run: |
          zizmor --offline --no-exit-codes ./
      
      - name: Run zizmor offline scan
        run: |
          zizmor --offline bad-workflow.yml
